name:  Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.docker_image }}
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - rolling
        include:
          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-jazzy-ros-base-latest
            ros_distribution: foxy
            ros_version: 2
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-humble-ros-base-latest
            ros_distribution: galactic
            ros_version: 2
          # Rolling Ridley  (June 2020 - Present)
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
            ros_distribution: rolling
            ros_version: 2
    steps:
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: osqp_vendor
          target-ros2-distro: ${{ matrix.ros_distribution }}
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                  "-DCMAKE_BUILD_TYPE=Release"
                ]
              }
            }
          skip-tests: true
